export enum ScoreTypes {
    acc = "acc",
    sens = "sens",
    spec = "spec",
    ppv = "ppv",
    npv = "npv",
    fbp = "fbp",
    fbn = "fbn",
    upm = "upm",
    gm = "gm",
    fm = "fm",
    mk = "mk",
    bm = "bm",
    mcc = "mcc",
    lrp = "lrp",
    lrn = "lrn",
    pt = "pt",
    dor = "dor",
    ji = "ji",
    bacc = "bacc",
    kappa = "kappa",
}
